```yaml
# schema_config.yaml
metadata:
  version: "1.0"
  last_updated: "2024-03-01"
  description: "Business analytics database schema and capabilities"

response_templates:
  greeting: |
    Hello! I'm your SQL Analytics Assistant. I can help you analyze:
    - Sales performance and trends
    - Customer behavior and segments
    - Product performance and inventory
    What would you like to know about?

  help: |
    I can help you analyze data from our business database. Here are some things I can do:
    {capabilities}
    
    Some example questions:
    {sample_questions}

  off_topic: |
    I'm specialized in business data analysis and can only help with questions about:
    {available_domains}
    
    Would you like to know what kind of analysis I can perform?

tables:
  sales_transactions:
    description: "Daily sales transactions with customer and product details"
    business_domain: "sales"
    create_statement: >
      CREATE TABLE sales_transactions (
        transaction_id INTEGER PRIMARY KEY,
        date TIMESTAMP,
        customer_id INTEGER,
        product_id INTEGER,
        store_id INTEGER,
        quantity INTEGER,
        unit_price DECIMAL(10,2),
        discount_amount DECIMAL(10,2),
        total_amount DECIMAL(10,2),
        payment_method VARCHAR(50),
        FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
        FOREIGN KEY (product_id) REFERENCES products(product_id),
        FOREIGN KEY (store_id) REFERENCES stores(store_id)
      )
    sample_questions:
      - "What were our total sales last month?"
      - "Show me daily sales trend"
      - "Which products have highest revenue?"
    visualization_hints:
      - type: "trend"
        columns: ["date", "total_amount"]
        chart: "line"
      - type: "comparison"
        columns: ["product_id", "total_amount"]
        chart: "bar"

  # ... [other table definitions remain same]

analysis_types:
  time_series:
    description: "Analyze trends over time"
    required_columns: ["date", "timestamp"]
    visualization: "line"
    aggregations: ["daily", "weekly", "monthly"]
    sample_phrases:
      - "trend"
      - "over time"
      - "daily/weekly/monthly"

  comparison:
    description: "Compare different categories/segments"
    visualization: "bar"
    aggregations: ["sum", "average", "count"]
    sample_phrases:
      - "compare"
      - "highest/lowest"
      - "top/bottom"

  distribution:
    description: "Analyze data distribution"
    visualization: "histogram"
    aggregations: ["count", "bucket"]
    sample_phrases:
      - "distribution"
      - "spread"
      - "range"

common_questions:
  sales_analysis:
    - question: "What were total sales by category?"
      required_tables: ["sales_transactions", "products"]
      visualization: "bar"
      
  customer_analysis:
    - question: "Who are our top customers?"
      required_tables: ["customers", "sales_transactions"]
      visualization: "bar"
      
  product_analysis:
    - question: "Show me product performance"
      required_tables: ["products", "sales_transactions"]
      visualization: "line"

sql_patterns:
  time_windows:
    last_month: "DATE_TRUNC('month', date_column) = DATE_TRUNC('month', DATEADD(month, -1, CURRENT_DATE()))"
    last_week: "DATE_TRUNC('week', date_column) = DATE_TRUNC('week', DATEADD(week, -1, CURRENT_DATE()))"
    
  aggregations:
    daily: "DATE_TRUNC('day', date_column)"
    monthly: "DATE_TRUNC('month', date_column)"
    
  rankings:
    top_n: "QUALIFY ROW_NUMBER() OVER (ORDER BY metric DESC) <= n"
    
  comparisons:
    year_over_year: """
    WITH current_year AS (...),
         prev_year AS (...)
    """

business_metrics:
  revenue:
    calculation: "SUM(total_amount)"
    aliases: ["sales", "income"]
    
  average_order_value:
    calculation: "AVG(total_amount)"
    aliases: ["aov", "average sale"]
    
  customer_lifetime_value:
    calculation: "SUM(total_amount) OVER (PARTITION BY customer_id)"
    aliases: ["ltv", "customer value"]

visualization_rules:
  - when: "time_series"
    use: "line"
    requires: ["date", "metric"]
    
  - when: "comparison"
    use: "bar"
    requires: ["category", "metric"]
    
  - when: "distribution"
    use: "histogram"
    requires: ["numeric_column"]
```

This enhanced config adds:
1. Response templates for different query types
2. Analysis types with sample phrases
3. SQL patterns for common scenarios
4. Business metrics definitions
5. Visualization rules
6. Common question templates

The agent uses these additional sections to:
1. Better understand query intent
2. Generate appropriate responses
3. Choose correct visualization
4. Follow SQL best practices
5. Map business terms to technical implementation

Would you like me to explain how any specific section is used by the agent?
